### PR TITLE
Fix for MSYS2

### PR DESCRIPTION
**Pull request by ghost**
Note: this fix is only for the MSYS subsystem of MSYS2.

### CODE REVIEW

**Comment by ghost** [comment]
@ldeniau I have also fixed Cygwin in the process. Please take a look at this. Thank you.

**Comment by ghost** [comment]
Is this project still being developed?

**Comment by ldeniau** [comment]
This project is on standby due to lack of time. I'd like to finalise a few things, but most of the main components are there... I also have to admit that I no longer use it for my own needs.

**Comment by ldeniau** [comment]
> Is this project still being developed?

Why did you close your PR?

**Comment by ghost** [comment]
> > Is this project still being developed?
> 
> Why did you close your PR?

Because I think the project is dead. Btw, I recreated the PR: https://github.com/CObjectSystem/COS/pull/51

Update: I decided to withdraw the PR. The COS library itself built fine, but there are problems with the test program (CosStd/example/ex01). On MINGW targets, it failed to link `strsignal`. I edited config.h to change `#define COS_HAS_STRSIGNAL 1` to `#define COS_HAS_STRSIGNAL 0` but it doesn't help. On MSYS target, the program crashed with segmentation fault. I don't know anything about the internals of this project so I'm unable to help any further. Goodbye.

**Pull request closed without merging**
